name: CI - Release to pypi

on:
  release:
    types: [published]

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  publish-pypi:
    name: Publish to pypi
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install package depenedencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Install release depenedencies
        run: |
          python -m pip install twine

      - name: Release
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
