name: Run tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test-setup-python:
    name: Test setup-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run with setup-python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install pylint
        run: python -m pip install pylint

      - name: Install flake8
        run: python -m pip install flake8

      # TODO make ci versions of make commands
      # - name: Run tests
      #   run: make test

      # - name: Run e2e tests
      #   run: make e2e_test
